# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97205d06d0fd380e4aec09dfae606a0f004fd66e20400c077067ac3f28f4caf05fcfac6c5440dd6f38274b8005897984e31355c6109cdaab466431c5e7b2b2a2

test:
  secret_key_base: 855c5e36dc68f865771773d69d36ae952b8eb17b96aafe61d13552e294577f4718123178096a71b3cc4a761d310a06fe36be694ed2cdbd5f9867297ee12bd243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
